language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  local-dir: dist
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  # repo: SingularData/singulardata.github.io
  # target-branch: master
  on:
    branch: master
  # provider: s3
  # access_key_id: $AWS_KEY_ID
  # secret_access_key: $AWS_SECRET_ACCESS_KEY
  # bucket: $AWS_S3_BUCKET
  # region: $AWS_REGION
  # local_dir: dist
  # skip_cleanup: true
  # acl: public_read
  # on:
  #   branch: master
